=== kbloom/appraisal-lexicon/lexicon-metadata.dtd
<!ELEMENT metadata (domain+,attribute*)>
<!ATTLIST metadata fileid CDATA #REQUIRED>
<!ELEMENT attribute (value|
   (maximum?,intermediate*,flippoint,intermediate*,minimum?))>
<!ATTLIST attribute domain CDATA #REQUIRED
	          name   CDATA #REQUIRED
		  type   (cline|taxonomy) #REQUIRED>
<!ELEMENT value (value*)>
<!ATTLIST value name CDATA #REQUIRED>
<!ELEMENT maximum EMPTY>
<!ATTLIST maximum name CDATA #REQUIRED>
<!ELEMENT minimum EMPTY>
<!ATTLIST minimum name CDATA #REQUIRED>
<!ELEMENT intermediate EMPTY>
<!ATTLIST intermediate name CDATA #REQUIRED>
<!ELEMENT flippoint EMPTY>
<!ATTLIST flippoint name CDATA #IMPLIED>

<!ELEMENT domain EMPTY>
<!ATTLIST domain name CDATA #REQUIRED>

=== kbloom/appraisal-lexicon/appraised-schemas.xml
<!DOCTYPE metadata SYSTEM "lexicon-metadata.dtd">
<metadata fileid="heirarchies">
   <domain name="movies"/>
   <domain name="products"/>

   <attribute name="appraisedtype" domain="movies" type="taxonomy">
      <value name="appraised-root">
      <value name="movie-thing">
	 <value name="movie">
	    <value name="this-movie"/>
	    <value name="other-movie"/>
	 </value>
	 <value name="person">
	    <value name="real">
	       <value name="actor"/>
	       <value name="admin">
		  <value name="writer"/>
		  <value name="director"/>
		  <value name="producer"/>
	       </value>
	    </value>
	    <value name="character"/>
	 </value>
	 <value name="aspect">
	    <value name="plot"/>
	    <value name="effects"/>
	    <value name="characterization"/>
	    <value name="set"/>
	 </value>
	 <value name="company">
	    <value name="this-company"/>
	    <value name="other-company"/>
	 </value>
	 <value name="marketing"/>
      </value>
      <value name="reference">
	 <value name="3rdperson"/>
	 <value name="deictic"/>
      </value>
      <value name="interactant">
	 <value name="1stperson"/>
	 <value name="2ndperson"/>
      </value>
      </value>
   </attribute>

   <attribute name="appraisedtype" domain="products" type="taxonomy">
      <value name="product-thing">
	 <value name="product">
	    <value name="specific">
	       <value name="this-product"/>
	       <value name="other-product"/>
	    </value>
	    <value name="type">
	       <value name="this-type"/>
	       <value name="other-type"/>
	    </value>
	 </value>
	 <value name="part"/>
	 <value name="aspect-operation"/>
	 <value name="company">
	    <value name="this-company"/>
	    <value name="other-company"/>
	 </value>
      </value>
   </attribute>
</metadata>
