=== kbloom/appraisal-lexicon/lexicon-phrases.dtd
<!ENTITY % modify-operations "(minimize|maximize|flip|increase|decrease|generalize)">
<!ENTITY % attribute "(base|modify|set)">

<!ELEMENT lexicon (lexeme*)>
<!ATTLIST lexicon fileid CDATA #REQUIRED>

<!ELEMENT lexeme (phrase,entry*)>
<!ELEMENT entry (constraints?,(%attribute;)*)>
<!ATTLIST entry domain CDATA #REQUIRED
		context CDATA #IMPLIED>

<!ELEMENT phrase (#PCDATA)>
<!ELEMENT constraints (pos)*>
<!ELEMENT pos (#PCDATA)>

<!ELEMENT modify EMPTY>
<!ATTLIST modify att CDATA #REQUIRED
	         type %modify-operations; #REQUIRED >
<!ELEMENT base EMPTY>
<!ATTLIST base att CDATA #REQUIRED
               value CDATA #REQUIRED>
<!ELEMENT set EMPTY>
<!ATTLIST set att CDATA #REQUIRED
              value CDATA #REQUIRED>

=== kbloom/appraisal-lexicon/movies.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lexicon SYSTEM "lexicon-phrases.dtd">
<lexicon fileid="moviewords">
   <lexeme>
      <phrase>climax</phrase>
      <entry domain="movies">
         <base att="appraisedtype" value="story"/>
      </entry>
   </lexeme>
   <lexeme>
      <phrase>drama</phrase>
      <entry domain="movies">
         <base att="appraisedtype" value="production"/>
      </entry>
   </lexeme>
   <lexeme>
      <phrase>sound effects</phrase>
      <entry domain="movies">
         <base att="appraisedtype" value="production"/>
      </entry>
   </lexeme>
  <lexeme>
    <phrase>everything</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="3rdperson"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>nothing</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="3rdperson"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>things</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="3rdperson"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>thing</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="3rdperson"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>something</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="3rdperson"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>content</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="story"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>denoument</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="story"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>dialogue</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="story"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>dialog</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="story"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>emotional tug</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="production"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>film making</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="production"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>gore</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="production"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>hit</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="this-movie"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>humor</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="production"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>storyline</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="story"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>performance</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="production"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>plot line</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="story"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>plot device</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="story"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>point of view</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="production"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>programming</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="production"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>premise</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="story"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>section</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="production"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>sections</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="production"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>situation</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="story"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>situations</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="story"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>violence</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="production"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>vocals</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="production"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>violence</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="production"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>story</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="story"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>moments</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="production"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>close-up</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="production"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>close-ups</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="production"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>ending</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="story"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>production</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="production"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>resolution</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="story"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>screen presence</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="production"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>setup</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="story"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>set-up</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="story"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>set up</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="story"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>setups</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="story"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>set-ups</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="story"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>set ups</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="story"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>length</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="production"/>
    </entry>
  </lexeme>
  <lexeme>
    <phrase>finale</phrase>
    <entry domain="movies">
      <base att="appraisedtype" value="story"/>
    </entry>
  </lexeme>
   <lexeme>
      <phrase>acted</phrase>
      <entry domain="movies">
         <base att="appraisedtype" value="production"/>
      </entry>
   </lexeme>
   <lexeme>
      <phrase>acting</phrase>
      <entry domain="movies">
         <base att="appraisedtype" value="production"/>
      </entry>
   </lexeme>
   <lexeme>
      <phrase>action</phrase>
      <entry domain="movies">
         <base att="appraisedtype" value="production"/>
      </entry>
   </lexeme>
   <lexeme>
      <phrase>actor</phrase>
      <entry domain="movies">
         <base att="appraisedtype" value="actor"/>
      </entry>
   </lexeme>
   <lexeme>
      <phrase>actors</phrase>
      <entry domain="movies">
         <base att="appraisedtype" value="actor"/>
      </entry>
   </lexeme>
   <lexeme>
      <phrase>antagonist</phrase>
      <entry domain="movies">
         <base att="appraisedtype" value="character"/>
      </entry>
   </lexeme>
   <lexeme>
      <phrase>atmosphere</phrase>
      <entry domain="movies">
         <base att="appraisedtype" value="production"/>
      </entry>
   </lexeme>
   <lexeme>
      <phrase>back stories</phrase>
      <entry domain="movies">
         <base att="appraisedtype" value="story"/>
      </entry>
   </lexeme>
   <lexeme>
      <phrase>back story</phrase>
      <entry domain="movies">
         <base att="appraisedtype" value="story"/>
      </entry>
   </lexeme>
   <lexeme>
      <phrase>baddie</phrase>
      <entry domain="movies">
         <base att="appraisedtype" value="character"/>
      </entry>
   </lexeme>
   <lexeme>
      <phrase>baddies</phrase>
      <entry domain="movies">
         <base att="appraisedtype" value="character"/>
      </entry>
   </lexeme>
   <lexeme>
      <phrase>bad guy</phrase>
      <entry domain="movies">
         <base att="appraisedtype" value="character"/>
      </entry>
   </lexeme>
   <lexeme>
      <phrase>bad guys</phrase>
      <entry domain="movies">
         <base att="appraisedtype" value="character"/>
      </entry>
   </lexeme>
   <lexeme>
      <phrase>cameo</phrase>
      <entry domain="movies">
         <base att="appraisedtype" value="production"/>
      </entry>
   </lexeme>
   <lexeme>
      <phrase>cameos</phrase>
      <entry domain="movies">
         <base att="appraisedtype" value="production"/>
      </entry>
   </lexeme>
   <lexeme>
      <phrase>cast</phrase>
      <entry domain="movies">
         <base att="appraisedtype" value="actor"/>
      </entry>
   </lexeme>
   <lexeme>
      <phrase>character</phrase>
      <entry domain="movies">
         <base att="appraisedtype" value="character"/>
      </entry>
   </lexeme>
   <lexeme>
      <phrase>characters</phrase>
      <entry domain="movies">
         <base att="appraisedtype" value="character"/>
      </entry>
   </lexeme>
   <lexeme>
      <phrase>comic relief</phrase>
      <entry domain="movies">
         <base att="appraisedtype" value="production"/>
      </entry>
   </lexeme>
   <lexeme>
      <phrase>computer-generated visuals</phrase>
      <entry domain="movies">
